version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "python"
    groups:
      python-runtime:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      python-development:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
          
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
          
