version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:15"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 3
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:15"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
