"""Compatibility facade for managed page-window helpers."""

from __future__ import annotations

from .managed.page_window import (
    _MAIN_AXES_BOUNDS,
    TYPE_CHECKING,
    Axes,
    Callable,
    Figure,
    LayoutEngineLike,
    LayoutScene,
    Managed2DPageWindowState,
    ManagedUiPalette,
    MatplotlibRenderer,
    _attach_controls,
    _GateTextCache,
    _ProjectedPage,
    _render_current_window,
    _sync_inputs,
    annotations,
    apply_page_window_axes_bounds,
    configure_page_window,
    dataclass,
    field,
    managed_ui_palette,
)

__all__ = [
    "Axes",
    "Callable",
    "Figure",
    "LayoutEngineLike",
    "LayoutScene",
    "Managed2DPageWindowState",
    "ManagedUiPalette",
    "MatplotlibRenderer",
    "TYPE_CHECKING",
    "_GateTextCache",
    "_MAIN_AXES_BOUNDS",
    "_ProjectedPage",
    "_attach_controls",
    "_render_current_window",
    "_sync_inputs",
    "annotations",
    "apply_page_window_axes_bounds",
    "configure_page_window",
    "dataclass",
    "field",
    "managed_ui_palette",
]
